package Model.Car;

/**
 * Not really an entity, just a part of car generated by factory
 */
public class CarBrand {

    private String name;

    /**
     * Default constructor
     */
    public CarBrand() {}
    
    public CarBrand(String name) {
	this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
