name: Deploy

on:
  release:
    types:
      - created
jobs:

    test:
        strategy:
            matrix:
                java: [ 13 ]
        env:
            MVN_FLAGS: "-Dproperties.java.version=${{ matrix.java }} -B clean"

        name: Pr title check
        runs-on: ubuntu-latest
        steps:
            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                  java-version: ${{ matrix.java }}

            - name: Publish artifact on GitHub Packages
              if: github.event.release.tag_name
              run: mvn ${MVN_FLAGS} deploy -DskipTests
              env:
                  VERSION: ${{ github.event.release.tag_name }}
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

            - uses: dev-drprasad/delete-tag-and-release@v0.1.3
              if: ${{ failure() }}
              with:
                  delete_release: true # default: false
                  tag_name: ${{ github.event.release.tag_name }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
