name: Build and run tests

on:
    pull_request:
        types:
            - opened
            - edited
            - synchronize

jobs:
    test:
        strategy:
            matrix:
                java: [ 13 ]
                os: [ ubuntu-latest, windows-latest ]
        name: Tests - ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        env:
            MVN_FLAGS: "-Dproperties.java.version=${{ matrix.java }} -B clean"

        steps:
            - uses: amannn/action-semantic-pull-request@v3.1.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              with:
                  requireScope: false
            - uses: actions/checkout@v1
            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                  java-version: ${{ matrix.java }}
            - name: Maven Package
              run: mvn ${MVN_FLAGS} package -DskipTests
            - name: Maven Verify
              run: mvn ${MVN_FLAGS} verify -Pintegration-test
