name: Build and run tests

on:
    push:
        branches: ['*']

jobs:
    test:
        strategy:
            matrix:
                java: [ 13 ]
                os: [ ubuntu-latest, windows-latest ]
        name: Tests - ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        env:
            MVN_FLAGS: "-Dproperties.java.version=${{ matrix.java }} -B clean"

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                  java-version: ${{ matrix.java }}
            - name: Maven Package
              run: mvn ${MVN_FLAGS} package -DskipTests
            - name: Maven Verify
              run: mvn ${MVN_FLAGS} verify -Pintegration-test
